/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface': '#1b1c1a',
        'inverse-on-surface': '#f2f1ed',
        'tertiary-fixed-dim': '#abcdc6',
        'outline': '#837470',
        'primary-fixed-dim': '#edbbaf',
        'on-secondary': '#ffffff',
        'on-background': '#1b1c1a',
        'on-tertiary-fixed': '#00201c',
        'on-primary-fixed': '#2f140d',
        'tertiary-container': '#5a7a74',
        'secondary-container': '#ebe1da',
        'primary-container': '#936a60',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#ffdad2',
        'surface-container-highest': '#e3e2df',
        'inverse-primary': '#edbbaf',
        'on-tertiary': '#ffffff',
        'tertiary': '#42615c',
        'on-primary': '#ffffff',
        'primary': '#785249',
        'tertiary-fixed': '#c7eae2',
        'primary-700': '#7D5A50',
        'error-container': '#ffdad6',
        'secondary-fixed': '#ebe1da',
        'on-secondary-fixed-variant': '#4c4641',
        'inverse-surface': '#30312e',
        'secondary-fixed-dim': '#cec5be',
        'neutral-900': '#050504',
        'on-secondary-container': '#6a635e',
        'background': '#faf9f5',
        'surface-container-high': '#e9e8e4',
        'on-secondary-fixed': '#1f1b17',
        'surface-dim': '#dbdad6',
        'surface-bright': '#faf9f5',
        'on-primary-fixed-variant': '#613e35',
        'secondary': '#645d58',
        'on-error-container': '#93000a',
        'error': '#ba1a1a',
        'surface': '#faf9f5',
        'on-tertiary-container': '#eefffa',
        'surface-container-low': '#f5f4f0',
        'on-tertiary-fixed-variant': '#2d4c47',
        'neutral-100': '#EEEDE9',
        'on-surface-variant': '#504441',
        'primary-50': '#F9F7F5',
        'surface-container': '#efeeea',
        'surface-variant': '#e3e2df',
        'surface-tint': '#7b554c',
        'outline-variant': '#d5c3be',
        'on-primary-container': '#fffaf9',
        'on-error': '#ffffff'
      },
      fontFamily: {
        'label-lg': ['Libre Caslon Text', 'serif'],
        'headline-md': ['SeoulHangang', 'serif'],
        'headline-lg-mobile': ['SeoulHangang', 'serif'],
        'body-md': ['Libre Caslon Text', 'serif'],
        'label-md': ['Libre Caslon Text', 'serif'],
        'headline-lg': ['SeoulHangang', 'serif'],
        'display-lg': ['SeoulHangang', 'serif'],
        'headline-sm': ['SeoulHangang', 'serif'],
        'body-sm': ['Libre Caslon Text', 'serif'],
        'body-lg': ['Libre Caslon Text', 'serif'],
      },
      fontSize: {
        'label-lg': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-md': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-sm': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }]
      },
      spacing: {
        'container-max': '1280px',
        'stack-md': '1.5rem',
        'stack-lg': '3rem',
        'gutter': '1.5rem',
        'stack-sm': '0.5rem',
        'section-padding-desktop': '6rem',
        'section-padding-mobile': '4rem'
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px'
      },
      animation: {
        blob: 'blob 7s infinite',
        'fade-in': 'fadeIn 0.6s ease-out',
        'fade-in-left': 'fadeInLeft 0.8s ease-out',
        'fade-in-right': 'fadeInRight 0.8s ease-out',
        'slide-up': 'slideUp 0.6s ease-out',
        'fade-in-up': 'fadeInUp 1.2s ease-out forwards',
      },
      keyframes: {
        blob: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
        },
        fadeIn: {
          'from': { opacity: '0', transform: 'translateY(20px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInLeft: {
          'from': { opacity: '0', transform: 'translateX(-50px)' },
          'to': { opacity: '1', transform: 'translateX(0)' },
        },
        fadeInRight: {
          'from': { opacity: '0', transform: 'translateX(50px)' },
          'to': { opacity: '1', transform: 'translateX(0)' },
        },
        slideUp: {
          'from': { opacity: '0', transform: 'translateY(30px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInUp: {
          'from': { opacity: '0', transform: 'translateY(40px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
